# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chess.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hess.proto\"\x1a\n\tChessGame\x12\r\n\x05moves\x18\x01 \x03(\t\")\n\x0c\x43hessDataSet\x12\x19\n\x05games\x18\x01 \x03(\x0b\x32\n.ChessGameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chess_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHESSGAME']._serialized_start=15
  _globals['_CHESSGAME']._serialized_end=41
  _globals['_CHESSDATASET']._serialized_start=43
  _globals['_CHESSDATASET']._serialized_end=84
# @@protoc_insertion_point(module_scope)
