[package]
name = "data-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shakmaty = "0.26"
anyhow = "1.0"
pgn-reader = "0.25"
chess = "3.2"
indicatif = "0.17"
